---
title: "t-SNE solution"
author: "ROTICH HARON"
date: "2/1/2022"
output: html_document
---

```{r}
install.packages('Rtsne')

```
```{r}
# loading library
library(Rtsne)
```
```{r}
train<- read.csv('http://bit.ly/MNISTDataset')  
```
```{r}
head(train)
```
```{r}
## Curating the database for analysis with both t-SNE and PCA
Labels<-train$label
train$label<-as.factor(train$label)
```

```{r}
colors = rainbow(length(unique(train$label)))
names(colors) = unique(train$label)
```
```{r}
tsne <- Rtsne(train[,-1], dims = 2, perplexity=30, verbose=TRUE, max_iter = 500)
exeTimeTsne<- system.time(Rtsne(train[,-1], dims = 2, perplexity=30, verbose=TRUE, max_iter = 500))
```
```{r}
## Plotting
plot(tsne$Y, t='n', main="tsne")
text(tsne$Y, labels=train$label, col=colors[train$label])
```

```{r}
## Challenge 1
# ---
# Question: Apply t-SNE on the Iris dataset. This help us to decide whether classes are separable 
# in some linear or nonlinear representation.
# ---
# OUR CODE GOES BELOW
# 
# 

```
# Loading our iris datset
```{r}
Iris <- iris
head(Iris)
```
```{r}
# encoding class variable
library(caret)

dmy <- dummyVars(" ~ .", data = iris, fullRank = T)
dat_transformed <- data.frame(predict(dmy, newdata = iris))

```
```{r}
# checking for duplicates
sum(duplicated(iris))

```
```{r}
install.packages("[dplyr")
```
```{r}
iris[!duplicated(iris)]

```
```{r}
## Curating the database for analysis with both t-SNE and PCA
Labels<-iris$Species
iris$Species <-as.factor(iris$Species)
```
```{r}
# plot
colors=rainbow(length(unique(iris$Species)))
names(colors)== unique(iris$Species)

```
```{r}
tsne <- Rtsne(iris[,-1], dims = 2, perplexity=30, verbose=TRUE, max_iter = 500)
exeTimeTsne<- system.time(Rtsne(train[,-1], dims = 2, perplexity=30, verbose=TRUE, max_iter = 500))
```